<a href="https://colab.research.google.com/github/sh1vam31/Complete_DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [ ]:
import numpy as np

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.



## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [9]:
import numpy as np

arr = np.array([0, 1, 2, 3])
print(arr)
print(type(arr))

arr = np.array(["0", 1, 2, 3])  # if we pass one string it will convert all the elements into the string
print(arr)
print(type(arr))

[0 1 2 3]
<class 'numpy.ndarray'>
['0' '1' '2' '3']
<class 'numpy.ndarray'>


Lets create a matrix using list

In [10]:
a = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(a)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **Built-in Methods**
there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [32]:
arr = np.zeros(4)   # create a normal 1D array
print(arr)
print()

arr1 = np.zeros([3,4])    # create a 2D metrix
print(arr1)
print()

arr2 = np.ones([2,2])
print(arr2)
print()

arr3 = np.full([2,2], 5)
print(arr3)
print()

arr4 = np.arange(1,11)
print(arr4)
print()

arr5 = np.linspace(1,10,7)    # linspace -> linear spacing arrange a number with eqal spacing
print(arr5)
print()

arr6 = np.eye(5)    # eye -> give an identity metrix
print(arr6)
print()

arr7 = np.random.rand(2,3)    # random.rand -> create a matrix with random numnber between 0 to 1
print(arr7)
print()

arr8 = np.random.randint(1,100,[2,3])
print(arr8)
print()

arr9 = np.random.randn(2,3)     # random.randn -> give the number between -3 to +3  (bell curve distribution)
print(arr9)
print()

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1.]
 [1. 1.]]

[[5 5]
 [5 5]]

[ 1  2  3  4  5  6  7  8  9 10]

[ 1.   2.5  4.   5.5  7.   8.5 10. ]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[0.3844686  0.81549103 0.61029686]
 [0.78369297 0.40016589 0.3687397 ]]

[[53 48  4]
 [85 28  2]]

[[-1.07940603 -0.59896796  0.04494009]
 [ 0.53985112  0.77101108 -0.01917495]]



# **1. Attributes of an Array**
Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.